# Generated by Django 4.2.11 on 2024-03-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_requests_brewery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='first_brewed',
            field=models.CharField(max_length=200),
        ),
    ]
