# Generated by Django 4.2.11 on 2024-03-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO users_review (
                id,
                beer_id,
                author_id,
                rating,
                body,
                is_approved,
                created_on,
                updated_on
            )
            SELECT
                id,
                beer_id,
                author_id,
                rating,
                body,
                is_approved,
                created_on,
                updated_on
            FROM
                catalog_review;
            SELECT setval(pg_get_serial_sequence('"users_review"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "users_review";
        """, reverse_sql="""
            INSERT INTO catalog_review (
                id,
                beer_id,
                author_id,
                rating,
                body,
                is_approved,
                created_on,
                updated_on
            )
            SELECT
                id,
                beer_id,
                author_id,
                rating,
                body,
                is_approved,
                created_on,
                updated_on
            FROM
                users_review;
        """)
    ]
