# Generated by Django 4.2.11 on 2024-03-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_requests_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
