# Generated by Django 4.2.10 on 2024-02-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tagline', models.CharField(max_length=200, unique=True)),
                ('first_brewed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('abv', models.IntegerField()),
                ('food_pairing', models.JSONField()),
            ],
        ),
    ]
