# Generated by Django 4.2.11 on 2024-03-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='beer_name',
            field=models.CharField(max_length=200),
        ),
    ]
