# Generated by Django 4.2.11 on 2024-07-04 17:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_requests_beer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='beer_image',
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
