# Generated by Django 4.2.10 on 2024-03-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
