# Generated by Django 4.2.10 on 2024-03-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_beer_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
