# Generated by Django 4.2.11 on 2024-03-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_requests'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO catalog_requests (
                id,
                user_id,
                beer_name,
                brewery_name,
                image,
                abv,
                first_brewed,
                comments,
                is_approved
            )
            SELECT
                id,
                user_id,
                beer_name,
                brewery_name,
                image,
                abv,
                first_brewed,
                comments,
                is_approved
            FROM
                users_requests;
            SELECT setval(pg_get_serial_sequence('"catalog_requests"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "catalog_requests";
        """, reverse_sql="""
            INSERT INTO users_requests (
                id,
                user_id,
                beer_name,
                brewery_name,
                image,
                abv,
                first_brewed,
                comments,
                is_approved
            )
            SELECT
                id,
                user_id,
                beer_name,
                brewery_name,
                image,
                abv,
                first_brewed,
                comments,
                is_approved
            FROM
                catalog_requests;
        """)
    ]